build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                override: [php-scrutinizer-run]

filter:
    excluded_paths:
        - 'Configuration/*'
        - 'Documentation/*'
        - 'Resources/*'
        - 'Tests/*'
    paths:
        - 'Classes/*'
tools:

    php_cpd:
        enabled: true

    php_code_sniffer:
        enabled: true
        config:
            standard: TYPO3CMS

    php_hhvm:
        enabled: true
        config:
            use_undeclared_constant: false

    php_mess_detector:
        enabled: true
        config:
            controversial_rules:
                superglobals: false

    php_pdepend:
        enabled: true

    php_analyzer:
        enabled: true
    # We generate code coverage during tests at travis and will send them here
    external_code_coverage:
        runs: 2
        timeout: 1200
