sudo: true

language: php

php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - TYPO3_VERSION="~7.6"
    - TYPO3_VERSION="~8.7"

matrix:
  fast_finish: true

install: make install

script:
  - make cgl
  - make unitTests

after_script:
  - make uploadCodeCoverage
  - make clean

cache:
  directories:
    - $HOME/.composer/cache
